services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: campusfix-app
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ..:/var/www
    environment:
      DB_CONNECTION: sqlite
    networks:
      - campusfix-network

networks:
  campusfix-network:
    driver: bridge

